jobs:
  include:
    - stage: test
      language: node_js
      node_js: '8.10.0'
      script:
        - yarn install --audit
        - yarn test
        - yarn build
        - export CYPRESS_BASE_URL=$(now -t $NOW_TOKEN)
        - yarn test:integration
        - yarn lh -- --perf=85 --pwa=100 $CYPRESS_BASE_URL

stages:
  - test

cache:
  directories:
    - web/.next
