jobs:
  include:
    - stage: test
      language: node_js
      node_js: '8.10.0'
      script:
        - yarn install --audit
        - yarn test
        - yarn build

    - stage: release
      language: node_js
      node_js: '8.10.0'
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn release; fi'

stages:
  - test
  - name: release
    if: branch = master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  directories:
    - web/.next
