jobs:
  include:
    - stage: test
      language: node_js
      node_js: '11'
      script:
        - yarn install --audit
        - yarn test
        - yarn build
        - export CYPRESS_BASE_URL=$(now -t $NOW_TOKEN)
        - yarn test:integration
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn lh -- --perf=70 --seo=90 --a11y=80 --bp=80 --pwa=100 $CYPRESS_BASE_URL; fi'

    - stage: release
      if: branch = master
      language: node_js
      node_js: '11'
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export CYPRESS_BASE_URL=$(now -t $NOW_TOKEN --target production) && yarn test:integration; fi'

stages:
  - test
  - release
  - deploy
