jobs:
  include:
    - stage: test
      language: node_js
      node_js: 'node'
      script:
        - yarn install --audit
        - yarn test
        - yarn build
        - export CYPRESS_BASE_URL=$(now -t $NOW_TOKEN)
        - yarn test:integration
        - if [ ! -z "$TRAVIS_PULL_REQUEST_SLUG" ] ; then yarn lh -- --perf=70 --seo=90 --a11y=80 --bp=80 --pwa=100 $CYPRESS_BASE_URL ; fi

    - stage: release
      if: branch = master AND env(TRAVIS_PULL_REQUEST) = false
      language: node_js
      node_js: 'node'
      script:
        - export CYPRESS_BASE_URL=$(now -t $NOW_TOKEN --target production)
        - yarn test:integration

stages:
  - test
  - release
  - deploy
